name: Daily build
on:
  schedule:
    - cron: "0 1 * * *" # Every day at 1:00 AM
  workflow_dispatch:
jobs:
  release_image_to_private_repo:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_REPOSITORY: andreaangiolillo22/atlascli_test
      PRIVATE_IMAGE_REPOSITORY: andreaangiolillo22/andrea-private
      PLATFORMS: linux/amd64,linux/arm64
      QUAY: quay.io
      DOCKER_CLI_EXPERIMENTAL: enabled # used for enabling containerd image storage. See https://github.com/docker/setup-buildx-action/issues/257#issuecomment-1722284952
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set date
        id: set-date
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo DATE=${DATE} >> $GITHUB_ENV
      - name: 'Get latest tag'
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: mongodb/mongodb-atlas-cli
          releases-only: true
          regex: 'atlascli*'
      - name: Extract version
        run: |
          release_tag=${{ steps.get-latest-tag.outputs.tag }}
          echo "LATEST_VERSION=${release_tag#*/}" >> $GITHUB_ENV
      - name: Enable containerd image store # See https://github.com/docker/setup-buildx-action/issues/257#issuecomment-1722284952
        uses: crazy-max/ghaction-setup-docker@v2
        with:
          version: v24.0.6
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_SECRET }}"
      - name: Build and push container to Dockerhub private repository
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.PRIVATE_IMAGE_REPOSITORY }}:latest ,
            ${{ env.PRIVATE_IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }} ,
            ${{ env.PRIVATE_IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }}-${{ env.DATE }}
          file: Dockerfile
          push: true
  release_image_to_public_repo:
    name: Build and publish docker image
    needs: [ release_image_to_private_repo ]
    runs-on: ubuntu-latest
    env:
      IMAGE_REPOSITORY: andreaangiolillo22/atlascli_test
      PRIVATE_IMAGE_REPOSITORY: andreaangiolillo22/andrea-private
      PLATFORMS: linux/amd64,linux/arm64
      QUAY: quay.io
      DOCKER_CLI_EXPERIMENTAL: enabled # used for enabling containerd image storage. See https://github.com/docker/setup-buildx-action/issues/257#issuecomment-1722284952
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set date
        id: set-date
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo DATE=${DATE} >> $GITHUB_ENV
      - name: 'Get latest tag'
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: mongodb/mongodb-atlas-cli
          releases-only: true
          regex: 'atlascli*'
      - name: Extract version
        run: |
          release_tag=${{ steps.get-latest-tag.outputs.tag }}
          echo "LATEST_VERSION=${release_tag#*/}" >> $GITHUB_ENV
      - name: Enable containerd image store # See https://github.com/docker/setup-buildx-action/issues/257#issuecomment-1722284952
        uses: crazy-max/ghaction-setup-docker@v2
        with:
          version: v24.0.6
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_SECRET }}"
      - name: Sign docker images with cosign
        env:
          PKCS11_URI: ${{ secrets.PKCS11_URI }}
          GRS_PASSWORD: ${{ secrets.GRS_PASSWORD }}
          GRS_USERNAME: ${{ secrets.GRS_USERNAME }}
          SIGNATURE_REPO: ${{ secrets.COSIGN_REPOSITORY_QUAY }}
          TEST_REGEX: "^TestAccSearchDeployment"
        run: |
          IMAGE=${{ env.PRIVATE_IMAGE_REPOSITORY }}:latest 
          echo "GRS_CONFIG_USER1_USERNAME=${GRS_USERNAME}" >> "signing-envfile"
          echo "GRS_CONFIG_USER1_PASSWORD=${GRS_PASSWORD}" >> "signing-envfile"
          echo "COSIGN_REPOSITORY=${SIGNATURE_REPO}" >> "signing-envfile"
          
          docker run \
            --env-file=signing-envfile \
            --rm \
            -v ~/.docker/config.json:/root/.docker/config.json \
            -v $(pwd):$(pwd) \
            -w $(pwd) \
            artifactory.corp.mongodb.com/release-tools-container-registry-local/garasign-cosign \
            cosign sign --key "${PKCS11_URI}" --tlog-upload=false ${IMAGE}
            
          ls -al
