name: PRs and Issue Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:
jobs:
  labeler:
    name: Add Label to PRs and Issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Needed by labeler
      issues: write # Needed by labeler
    steps:
      - name: Checkout your code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: srvaroa/labeler@1eec6d9e7c5fa5864840279978680302f955fc37
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          use_local_config: true
          config_path: .github/labeler.yaml
  slack-notification-doc-team:
    needs: labeler
    if: ${{ contains(github.event.pull_request.labels.*.name, 'need-doc-review') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: pr-title-slack-doc
          append: true
          message: "APIx Bot :bowtie:: a message has been sent to Docs Slack channel :rocket:."