name: PRs and Issue Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
jobs:
  labeler:
    env:
      GITHUB_TOKEN: ${{ secrets.TEST_TT }}
    name: Add Label to PRs and Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: srvaroa/labeler@1eec6d9e7c5fa5864840279978680302f955fc37
        with:
          use_local_config: true
          config_path: .github/labeler.yaml