name: PRs and Issue Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:
jobs:
  labeler:
    name: Add Label to PRs and Issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Needed by labeler
      issues: write # Needed by labeler
    steps:
      - name: Checkout your code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: srvaroa/labeler@1eec6d9e7c5fa5864840279978680302f955fc37
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          use_local_config: true
          config_path: .github/labeler.yaml
