name: Sends notifications after a PR is labeled
on:
  issues:
    types: [opened, edited]
  pull_request:
    types:
      - labeled

  workflow_dispatch:
jobs:
  slack-notification-doc-team:
    needs: labeler
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - name: Print PR labels
        run: echo "${{ github.event.pull_request.labels.*.name }}"
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        if: contains(github.event.pull_request.labels.*.name, 'need-doc-review')
        with:
          header: pr-title-slack-doc
          delete: true
      - uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        if: contains(github.event.pull_request.labels.*.name, 'need-doc-review')
        with:
          header: pr-title-slack-doc
          append: true
          message: "APIx Bot :bowtie:: a message has been sent to Docs Slack channel :rocket:."